config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'application#home'  # Set this to your homepage or other desired controller/action

  get 'home', to: 'application#home'

  resources :users
  resources :blogs
  resources :beats

  resources :analyze, only: [:index] do
    collection do
      post 'upload'
    end
  end

  resources :mastering, only: [:index] do
    collection do
      post 'upload'
    end
  end

  namespace :admin do 
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get 'dashboard', to: 'users#admin_dashboard'
  end

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
    
  end

  def edit
  end

  def show
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'Blog was successfully deleted.'
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find_by(id: params[:id])
    redirect_to blogs_path, alert: 'Blog not found' if @blog.nil?
  end

  def validate_user
    unless @blog.user == current_user
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to blogs_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card" style="position: relative; z-index: 5; bottom: 250px;">
      <div class="card-header text-center bg-dark text-light">
        <h2>Edit Post</h2>
      </div>
      <div class="card-body p-5">
        <%= form_with model: @blog, url: blog_path(@blog), method: :patch do |form| %>
          <div class="form-group mb-3">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= form.label :content %>
            <%= form.text_area :content, class: 'form-control' %>
          </div>
          <div class="actions text-center">
            <%= form.submit 'Update Post', class: 'btn btn-info col-6 mt-3' %>
          </div>
        <% end %>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="d-flex justify-content-center">
  <div class="text-center">
    <h1 class="mb-3">Producer<i>STACK</i> Blog</h1>
  </div>
</div>
<div class="d-flex justify-content-center">
  <div class="p-3">
    <%= link_to "New Blog Post", new_blog_path, class: "btn btn-info mt-3" %>
  </div>
</div>



<div class="d-flex justify-content-center"> 
  <div class="row mb-3">
    <% @blogs.each do |blog| %>
      <div class="col-4 p-4">
        <div class="card h-100">
          <%= image_tag "producer_stack.svg", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title text-center"><%= link_to blog.title, blog_path(blog) %></h5>
            <hr>
            <p class="card-text"><%= blog.content %></p>
          </div>
          <div class="card-footer">
            <small class="text-muted float-end"> <%= blog.updated_at.strftime('%B %e, %Y %l:%M %p') %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card" style="position: relative; z-index: 5; bottom: 250px;">
      <div class="card-header text-center bg-dark text-light">
        <h2>New Post</h2>
      </div>
      <div class="card-body p-5">
        <%= form_with model: @blog, url: blogs_path do |form| %>
          <div class="form-group mb-3">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= form.label :content %>
            <%= form.text_area :content, class: 'form-control' %>
          </div>
          <div class="actions text-center">
            <%= form.submit 'Create Post', class: 'btn btn-info col-6 mt-3' %>
          </div>
        <% end %>
        <hr>
        <div class="text-center">
          <div class="actions">
            <%= link_to "Cancel", blogs_path(@blog), class: "btn btn-dark mt-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="d-flex justify-content-center"> 
  <div class="row mb-3">
    <div class="col">
      <div class="card h-100 blog-card"> 
        <%= image_tag "producer_stack.svg", class: "card-img-top blog-img p-3" %> 
        <div class="card-body d-flex flex-column"> 
          <h5 class="card-title text-center"><%= @blog.title %></h5>
          <hr>
          <div class="flex-grow-1 overflow-auto text-center"> 
            <p class="card-text text-wrap p-4"><%= @blog.content %></p>
          </div>
        </div>
        <div class="card-footer">
          <small class="text-muted float-end">
            <%= @blog.updated_at.in_time_zone("Mountain Time (US & Canada)").strftime('%B %e, %Y %l:%M %p %Z') %>
          </small>
        </div>
        <div class="d-flex">
          <div class="ms-auto p-1">
          <% if @blog.user == current_user %>
            <%= link_to "Edit", edit_blog_path(@blog), class: "btn btn-info mt-3" %>
            <%= link_to "Delete", blog_path(@blog), method: :delete, data: { confirm: "Are you sure you want to delete this blog?" }, class: "btn btn-danger mt-3" %>
          <% end %>
            <%= link_to "Back", blogs_path, class: "btn btn-dark mt-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>