config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'application#home'  # Set this to your homepage or other desired controller/action

  get 'home', to: 'application#home'

  resources :users
  resources :blogs
  resources :beats

  resources :analyze, only: [:index] do
    collection do
      post 'upload'
    end
  end

  resources :mastering, only: [:index] do
    collection do
      post 'upload'
    end
  end

  namespace :admin do 
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get 'dashboard', to: 'users#admin_dashboard'
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :beats, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {admin: 0, basic: 1}

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show 
    @user = set_user
    @blogs = @user.blogs
  end

  def admin_dashboard 
    @user = current_user
    @users = User.all
    @blogs = Blog.all
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    build_resource(signup_params)

    if resource.save
      sign_up(resource_name, resource)
      redirect_to after_sign_up_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      flash[:error] = resource.errors.full_messages.to_sentence
      redirect_to new_user_registration_path
    end
  end

  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def signup_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, flash: { notice: 'User was successfully updated.' }
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by_id(params[:id])
    redirect_to users_url, alert: 'User not found' if @user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card" style="z-index: 5; bottom: 250px; ">
      <div class="card-header text-center bg-dark text-light">
        <h2>Edit</h2>
      </div>
      <div class="card-body p-5">
        <%= form_for(@user, url: user_path(@user), method: :patch) do |f| %>
          <div class="field mb-1">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, class: "form-control" %>
          </div>

          <div class="field mb-1">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, class: "form-control" %>
          </div>

          <div class="field mb-1">
            <%= f.label :email %><br />
            <%= f.email_field :email, class: "form-control" %>
          </div>

          <div class="field mb-1">
            <%= f.label :password %><br />
            <%= f.password_field :password, class: "form-control", required: true %>
          </div>

          <div class="field mb-1">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, class: "form-control", required: true %>
          </div>

          <div class="actions text-center">
            <%= f.submit "Confirm", class: "btn btn-info col-6 mt-3" %>
          </div>
        <% end %>
        <hr>
        <div class="text-center">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h2 class="text-center me-3">Community</h2>
      <div class="row">
        <div class="col-lg-12 mb-4">
          <table class="table table-striped text-center">
            <thead class="table-dark">
              <tr>
                <th>User Name</th>
                <th>Blogs</th>
                <th>Beats</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |u| %>
                <tr>
                  <td><%= link_to u.full_name, user_path(u) %></td>
                  <td><%= u.blogs.count %></td>
                  <td><%= u.beats.count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center text-center">
    <div class="col-md-10">
      <h2 class="m-3"><%= @user.full_name %>'s Profile</h2>
      <div class="row">
        <div class="col-lg-12 mb-4">
          <h2 class="m-4">Blog Posts</h2>
          <div style="overflow: auto; max-height: 400px;">
            <% if @user.blogs.present? %>
              <table class="table table-bordered table-striped text-center">
                <thead class="table-dark">
                  <tr>
                    <th>Blog Title</th>
                    <th>Content</th>
                  </tr>
                </thead>
                <tbody>
                  <% @user.blogs.each do |blog| %>
                    <tr>
                      <td><%= link_to blog.title, blog_path(blog) %></td>
                      <td><%= truncate_words(blog.content, 5) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
              <p>No blogs posted.</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 mb-4">
        <h2 class="text-center me-3">Beats</h2>
          <% if @user.beats.present? %>
            <table class="table table-bordered table-striped text-center">
              <thead class="table-dark">
                <tr>
                  <th>Artist</th>
                  <th>Title</th>
                </tr>
              </thead>
              <tbody>
                <% @user.beats.each do |beat| %>
                  <tr>
                    <td><%= beat.artist %></td>
                    <td><%= beat.title %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No beats uploaded.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="text-center">
      <div class="actions m-4">
        <% if current_user&.admin? || (current_user == @user) %>
          <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-info mt-3" %>
          <%= link_to "Delete Account", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-danger mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>