config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'application#home'  # Set this to your homepage or other desired controller/action

  get 'home', to: 'application#home'

  resources :users
  resources :blogs
  resources :beats

  resources :analyze, only: [:index] do
    collection do
      post 'upload'
    end
  end

  resources :mastering, only: [:index] do
    collection do
      post 'upload'
    end
  end

  namespace :admin do 
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get 'dashboard', to: 'users#admin_dashboard'
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark text-white pt-5 mt-5 text-center">
	<div class="footer-content pb-3">
		<div class="container">
			<div class="row">
				<!-- Footer widget 1 -->
				<div class="col-md-6">
					<div>
						<%= image_tag "Producer_stack-removebg-preview.png", style: "height: 150px;" %>
            <p>The innovative, proactive, music producer community.</p>
					</div>
				</div>
				<div class="col-md-5 mt-3">
					<div>
						<i class="ti-email newsletter-icon"></i>
						<h1 class="mb-2">Join the Producer Stack Team.</h1>
						<div class="form-group mb-0">
							<button class="btn btn-danger mb-3">Join us</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr>
		<div class="row mt-3"></div>
			<div class=" text-center mt-3">
				<div class="copyright-text">©2023 All Rights Reserved by <a href="#!">Producer Stack</a></div>
			</div>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('producer_stack.png') %>
    <title>ProducerStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'essentia', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag 'wavesurfer-config' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/es-module-shims@1.8.0/es-module-shims.min.js"></script>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/essentia.js@4.1.0/dist/essentia.min.js' %>

  </head>

  <body>
    <!-- ===========NAVBAR============ -->
    <nav class="navbar navbar-dark bg-dark sticky-top navbar-dark fixed-top">
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <div class="navbar-brand">
              <% if user_signed_in? %>
                <%= link_to user_path(current_user), class: "dropdown-item" do %>
                  <%= image_tag("Producer_stack-removebg-preview.png", alt: "Profile Image", style: "height: 150px;") %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"><b>Producer</b><i>Stack</i></h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= user_path(current_user) %>">Home</a>
                  <a class="nav-link active" aria-current="page" href="<%= new_beat_path %>">Upload Beats</a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
              <% else %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                </li>
                <li class="nav-item">
                  <%= button_to "Sign In", new_user_session_path, class: "btn btn-info dropdown-item" %>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
              <% end %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  More
                </a>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <% if user_signed_in? && current_user.role == "admin" %>
                    <li><a class="dropdown-item" href="<%= admin_dashboard_path %>">Admin Dashboard</a></li>
                  <% end %>
                  <!-- dashboard path needed? !-->
                  <li><a class="dropdown-item" href="<%= users_path %>">Community</a></li>
                  <li><a class="dropdown-item" href="<%= blogs_path %>">Blog</a></li>
                  <li><a class="dropdown-item" href="<%= beats_path %>">Beats</a></li>
                  <li><a class="dropdown-item" href="<%= analyze_index_path %>">Analyze Beats</a></li>
                  <li><a class="dropdown-item" href="<%= mastering_index_path %>">Master Beats</a></li>
                  <hr class="dropdown-divider">
                  <% if current_user %>
                    <li><%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %></li>
                    <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-info dropdown-item" %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <!-- ===========END NAVBAR============ -->

    <div class=" <%= set_background %> hero p-5 mb-4">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold text-light">Producer<i>STACK</i> is <b>HERE.</b></h1>
        <p class="col-md-5 text-light">The innovative, proactive, music producer community solution.</p>
        <a class="btn btn-outline text-light bg-danger" href="#">Learn More</a>
      </div>
    </div>
    
    <div class="container-fluid">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>